### PR TITLE
return UserLimit on callback exit (and detect UserLimit in other cases)

### PR DESCRIPTION
**Pull request by mlubin**
CC @joehuchette

### CODE REVIEW

**Comment by joehuchette** [comment]
:+1: This is the last solver to update, correct?

**Comment by mlubin** [comment]
Yep, but if we tag now we'll break the JuMP release

**Comment by joehuchette** [comment]
How far are we from tagging a new release? (i.e. how long do you want to kick the tires on the NLP stuff)

**Comment by mlubin** [comment]
At least another couple of weeks.

**Pull request merged**
