### PR TITLE
Fix solver option handling: `names` was deprecated in favor of `fieldnames`

### PR DESCRIPTION
**Pull request by czlee**
This error was happening:
```
ERROR: LoadError: type DataType has no field names
 in model at /home/czlee/.julia/v0.4/GLPKMathProgInterface/src/GLPKInterfaceMIP.jl:187
 in buildInternalModel at /home/czlee/.julia/v0.4/JuMP/src/solvers.jl:236
 in solve at /home/czlee/.julia/v0.4/JuMP/src/solvers.jl:77
 [inlined code] from util.jl:155
...
```

I think the issue occurred because `typeof(lpm.param).names` stopped making sense when they deprecated `names` in favor of `fieldnames` at https://github.com/JuliaLang/julia/pull/10332, and changed `DataType.names` to `DataType.name.names` in https://github.com/JuliaLang/julia/commit/afd4eb038dcd9fa3e512509f4c332a9e7763ba59, both of which are introduced in Julia 0.4.

`fieldnames` isn't defined in Julia 0.3 though (as far as I can tell), so I presume this would break 0.3 compatibility.

I'm new to Julia, so apologies if I got something wrong.

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks! Are there any tests you could add to ``test/runtests.jl`` which would catch this issue? It seems to have gone unnoticed for quite a while.

**Comment by czlee** [comment]
I'm sure that shouldn't be too hard, it was a pretty reliable bug. It should be reproducible when passing pretty much any option to `GLPKSolverMIP` and then attempting to run the solver. I'm using JuMP, which might complicate things a little with my (lack of) understanding of how `GLPKSolverMIP` is used, but will have a think about short snippets to test for it that don't rely on other packages. :smiley:

**Comment by mlubin** [comment]
[here](https://github.com/JuliaOpt/GLPKMathProgInterface.jl/blob/master/test/runtests.jl#L12) you could add a call to ``mixintprogtest`` with some options

**Comment by czlee** [comment]
Since I know the bug occurs in the `model` function, the easiest and narrowest (and least redundant) test would be just to add something like:
```julia
GLPKInterfaceLP.model(GLPKSolverLP(it_lim=-1))
GLPKInterfaceMIP.model(GLPKSolverMIP(it_lim=-1))
```
to runtests.jl. (Either it runs without error or it doesn't.)

Alternatively as you suggest I could add:
``` julia
linprogsolvertest(GLPKSolverLP(it_lim=-1))
mixintprogtest(GLPKSolverMIP(it_lim=-1))
```

It's worth noting here that the `it_lim=-1` should (in theory) do absolutely nothing to the solver: `-1` is the default for the `ItLim` parameter. I worry that putting in more interesting options, e.g. `it_lim=1000` or `tol_obj=1e-2`, would throw off the tests that check the actual solutions. I mean, those options don't cause tests to fail now (I tried), but given that the tests are in a different package, you presumably don't want a test whose purpose is to check option handling, to cause a test to fail because the return solution wasn't the true optimum. (Say, if MathProgInterface changes its tests in future, and the new tests wouldn't be valid tests when run with our options here.)

Do you have a view on which is preferable?

**Comment by mlubin** [comment]
Yes, I would avoid setting options that could result in early termination. Something like ``msg_lev`` seems harmless though.

**Comment by carlobaldassi** [comment]
Compatibility with julia 0.3 should be ensured by `Compat`, which defines `fieldnames`.
My preference for testing is to do it directly (first option).

**Comment by mlubin** [comment]
@carlobaldassi, for the first option, it would be nice to test that the options are actually set and not ignored. What's a good way to do this?

**Comment by czlee** [comment]
I added the first option, and also some tests to check that the parameters were in fact set, by checking the `param` and `smplxparam` members of the returned models. Because the models aren't used to try to solve the test problems, I just picked arbitrary values that are unlikely to be defaults.

**Comment by mlubin** [comment]
Thanks!

**Pull request merged**
